### ISSUE TITLE
Validator does not work under Windows

### ISSUE THREAD

**Issue by davidhoksza** [LDWLab/RNA2D-data-schema#8]
When running the validator under Windows, it throws the following error:

```
c:\projects\git\RNA2D-data-schema>validateJSON.py EC_LSU_3D_l.json
Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "C:\Python39\lib\site-packages\jsonschema\_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'file://C:\\projects\\git\\RNA2D-data-schema\\sections/rna-complex.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\urllib\request.py", line 1503, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [WinError 2] The system cannot find the file specified: '\\rna-complex.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 863, in resolve_remote
    with urlopen(uri) as url:
  File "C:\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Python39\lib\urllib\request.py", line 1481, in file_open
    return self.open_local_file(req)
  File "C:\Python39\lib\urllib\request.py", line 1520, in open_local_file
    raise URLError(exp)
urllib.error.URLError: <urlopen error [WinError 2] The system cannot find the file specified: '\\rna-complex.json'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\git\RNA2D-data-schema\validateJSON.py", line 142, in <module>
    main()
  File "C:\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\projects\git\RNA2D-data-schema\validateJSON.py", line 133, in main
    validate(data, schema, os.path.abspath(sections))
  File "C:\projects\git\RNA2D-data-schema\validateJSON.py", line 102, in validate
    for error in validator.iter_errors(data):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 328, in iter_errors
    for error in errors:
  File "C:\Python39\lib\site-packages\jsonschema\_validators.py", line 282, in properties
    for error in validator.descend(
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 328, in iter_errors
    for error in errors:
  File "C:\Python39\lib\site-packages\jsonschema\_legacy_validators.py", line 55, in items_draft3_draft4
    for error in validator.descend(item, items, path=index):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 328, in iter_errors
    for error in errors:
  File "C:\Python39\lib\site-packages\jsonschema\_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "C:\Python39\lib\site-packages\jsonschema\validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: <urlopen error [WinError 2] The system cannot find the file specified: '\\rna-complex.json'>
```

**Comment by CaedenMeade** [comment]
Hello, David, please try running this again. I've pushed an update, and it works on my machine.

**Comment by davidhoksza** [comment]
Works on mine, too. Thx.
